# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NPM install, build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run compile-gh --camera=github-linux-environment 
    - name : Upload
      uses: actions/upload-artifact@master
      with:
         name: odc-api
         path: compiled/dashcam-api.js
    - uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://hdc-firmware/cicd-test/dbs
        destination: ./compiled
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-west-2
        flags: --recursive
    - name: Download reference data from s3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://hdc-firmware/cicd-test/reference/
        destination: ./reference
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-west-2
        flags: --recursive
    - run: ls -l ./reference
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: ls -l ./compiled
    - run: python transform_times.py
    - run: ls -l ./compiled/mnt/data
    - run: ls -l ./compiled/tmp/recording/pic | wc -l
    - run: bash test.sh
    - name: Upload odc-api log as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: odc-api-log
        path: ./compiled/dashcam-logs.log
    # For some reason upload-artifact is not grabbing subdirectories
    - run: tar cvfz framekm-metadata.tar.gz ./compiled/mnt/data
    - name: Upload framekm metadata files
      uses: actions/upload-artifact@v4
      with:
        name: framekm-metadata
        path: ./framekm-metadata.tar.gz
    - name: Evaluate the end state of the test
      run: bash test_finish.sh
