# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NPM install, build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run compile-gh --camera=hdc 
    # - name : Upload
    #   uses: actions/upload-artifact@master
    #   with:
    #      name: odc-api
    #      path: compiled/dashcam-api.js
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Download file from S3
      run: |
        aws s3 cp s3://hdc-firmware/cicd-test/dbs/data-logger.v1.4.5.db ./compiled
        aws s3 cp s3://hdc-firmware/cicd-test/dbs/data-logger.v1.4.5.db-shm ./compiled
        aws s3 cp s3://hdc-firmware/cicd-test/dbs/data-logger.v1.4.5.db-wal ./compiled
        ls -l ./compiled

