# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ODC API End to End Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run compile-gh --camera=github-linux-environment
    - name: Download the end-to-end test data
      run: bash download_test_data.sh
      working-directory: ./end-to-end-test
    - run: ls -lR ./end-to-end-test/tests
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: ls -l ./end-to-end-test
    - run: python ./transform_times.py
      working-directory: ./end-to-end-test
    - run: ls -l ./end-to-end-test/mnt/data
    - run: ls -l ./end-to-end-test/tmp/recording/pic | wc -l
    - run: bash test.sh
      working-directory: ./end-to-end-test
    - name: Upload odc-api log as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: odc-api-log
        path: ./compiled/dashcam-logs.log
    # For some reason upload-artifact is not grabbing subdirectories
    - run: tar cvfz framekm-metadata.tar.gz ./end-to-end-test/mnt/data
    - name: Upload framekm metadata files
      uses: actions/upload-artifact@v4
      with:
        name: framekm-metadata
        path: ./framekm-metadata.tar.gz
    - name: Evaluate the end state of the test
      run: bash test_finish.sh
      working-directory: ./end-to-end-test
